basePath: /
definitions:
  main.User:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  main.UserForm:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for demonstrating Swagger with Echo.
  title: Echo Swagger Example API
  version: "1.0"
paths:
  /submit-form:
    post:
      consumes:
      - multipart/form-data
      description: Submit name and age via form-data (multipart)
      parameters:
      - description: User name
        in: formData
        name: name
        required: true
        type: string
      - description: User age
        in: formData
        name: age
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.UserForm'
      summary: Submit user via form-data
      tags:
      - form
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.User'
            type: array
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: User to create
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.User'
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
